name: 'Strip Markdown Github Action'
description: 'Strip markdown to text'
author: 'dishank-infurnia'
inputs:
  markdown:
    description: 'Markdown to be converted to text'
    required: true
  jiraEmail:
    description: 'Jira Email for jira integration'
    required: true
  jiraApiToken:
    description: 'Jira API token for jira integration'
    required: true
  jiraBaseUrl: 
    description: 'Jira Cloud base url'
    required: true
  jiraSprintID:
    description: 'Jira sprint ID'
    default: 'None'
  jiraReleaseID:
    description: 'Jira release ID'
    default: 'None'
  releaseEnv:
    description: 'Environment of release for Jira'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
